/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
pub type int8_t = i8;
pub type int16_t = i16;
pub type int32_t = i32;
pub type int64_t = i64;
pub type uint8_t = u8;
pub type uint16_t = u16;
pub type uint32_t = u32;
pub type uint64_t = u64;
pub type int_least8_t = ::std::os::raw::c_char;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_long;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulong;
pub type int_fast8_t = ::std::os::raw::c_char;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intptr_t = isize;
pub type uintptr_t = usize;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum AMFDataType {
    AMF_NUMBER = 0,
    AMF_BOOLEAN = 1,
    AMF_STRING = 2,
    AMF_OBJECT = 3,
    AMF_MOVIECLIP = 4,
    AMF_NULL = 5,
    AMF_UNDEFINED = 6,
    AMF_REFERENCE = 7,
    AMF_ECMA_ARRAY = 8,
    AMF_OBJECT_END = 9,
    AMF_STRICT_ARRAY = 10,
    AMF_DATE = 11,
    AMF_LONG_STRING = 12,
    AMF_UNSUPPORTED = 13,
    AMF_RECORDSET = 14,
    AMF_XML_DOC = 15,
    AMF_TYPED_OBJECT = 16,
    AMF_AVMPLUS = 17,
    AMF_INVALID = 255,
}
#[derive(Copy, Clone)]
#[repr(u32)]
#[derive(Debug)]
pub enum AMF3DataType {
    AMF3_UNDEFINED = 0,
    AMF3_NULL = 1,
    AMF3_FALSE = 2,
    AMF3_TRUE = 3,
    AMF3_INTEGER = 4,
    AMF3_DOUBLE = 5,
    AMF3_STRING = 6,
    AMF3_XML_DOC = 7,
    AMF3_DATE = 8,
    AMF3_ARRAY = 9,
    AMF3_OBJECT = 10,
    AMF3_XML = 11,
    AMF3_BYTE_ARRAY = 12,
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct AVal {
    pub av_val: *mut ::std::os::raw::c_char,
    pub av_len: ::std::os::raw::c_int,
    _bindgen_padding_0_: [u8; 4usize],
}
impl ::std::default::Default for AVal {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct AMFObject {
    pub o_num: ::std::os::raw::c_int,
    pub o_props: *mut AMFObjectProperty,
}
impl ::std::default::Default for AMFObject {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct AMFObjectProperty {
    pub p_name: AVal,
    pub p_type: AMFDataType,
    pub p_vu: Union_Unnamed1,
    pub p_UTCoffset: int16_t,
    _bindgen_padding_0_: [u8; 6usize],
}
impl ::std::default::Default for AMFObjectProperty {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct Union_Unnamed1 {
    pub _bindgen_data_: [u64; 2usize],
}
impl Union_Unnamed1 {
    pub unsafe fn p_number(&mut self) -> *mut f64 {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn p_aval(&mut self) -> *mut AVal {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
    pub unsafe fn p_object(&mut self) -> *mut AMFObject {
        let raw: *mut u8 = ::std::mem::transmute(&self._bindgen_data_);
        ::std::mem::transmute(raw.offset(0))
    }
}
impl ::std::default::Default for Union_Unnamed1 {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
#[repr(C)]
#[derive(Copy, Clone)]
#[derive(Debug)]
pub struct AMF3ClassDef {
    pub cd_name: AVal,
    pub cd_externalizable: ::std::os::raw::c_char,
    pub cd_dynamic: ::std::os::raw::c_char,
    pub cd_num: ::std::os::raw::c_int,
    pub cd_props: *mut AVal,
}
impl ::std::default::Default for AMF3ClassDef {
    fn default() -> Self { unsafe { ::std::mem::zeroed() } }
}
extern "C" {
    pub fn AMF_EncodeString(output: *mut ::std::os::raw::c_char,
                            outend: *mut ::std::os::raw::c_char,
                            str: *const AVal) -> *mut ::std::os::raw::c_char;
    pub fn AMF_EncodeNumber(output: *mut ::std::os::raw::c_char,
                            outend: *mut ::std::os::raw::c_char, dVal: f64)
     -> *mut ::std::os::raw::c_char;
    pub fn AMF_EncodeInt16(output: *mut ::std::os::raw::c_char,
                           outend: *mut ::std::os::raw::c_char,
                           nVal: ::std::os::raw::c_short)
     -> *mut ::std::os::raw::c_char;
    pub fn AMF_EncodeInt24(output: *mut ::std::os::raw::c_char,
                           outend: *mut ::std::os::raw::c_char,
                           nVal: ::std::os::raw::c_int)
     -> *mut ::std::os::raw::c_char;
    pub fn AMF_EncodeInt32(output: *mut ::std::os::raw::c_char,
                           outend: *mut ::std::os::raw::c_char,
                           nVal: ::std::os::raw::c_int)
     -> *mut ::std::os::raw::c_char;
    pub fn AMF_EncodeBoolean(output: *mut ::std::os::raw::c_char,
                             outend: *mut ::std::os::raw::c_char,
                             bVal: ::std::os::raw::c_int)
     -> *mut ::std::os::raw::c_char;
    pub fn AMF_EncodeNamedString(output: *mut ::std::os::raw::c_char,
                                 outend: *mut ::std::os::raw::c_char,
                                 name: *const AVal, value: *const AVal)
     -> *mut ::std::os::raw::c_char;
    pub fn AMF_EncodeNamedNumber(output: *mut ::std::os::raw::c_char,
                                 outend: *mut ::std::os::raw::c_char,
                                 name: *const AVal, dVal: f64)
     -> *mut ::std::os::raw::c_char;
    pub fn AMF_EncodeNamedBoolean(output: *mut ::std::os::raw::c_char,
                                  outend: *mut ::std::os::raw::c_char,
                                  name: *const AVal,
                                  bVal: ::std::os::raw::c_int)
     -> *mut ::std::os::raw::c_char;
    pub fn AMF_DecodeInt16(data: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_ushort;
    pub fn AMF_DecodeInt24(data: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_uint;
    pub fn AMF_DecodeInt32(data: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_uint;
    pub fn AMF_DecodeString(data: *const ::std::os::raw::c_char,
                            str: *mut AVal);
    pub fn AMF_DecodeLongString(data: *const ::std::os::raw::c_char,
                                str: *mut AVal);
    pub fn AMF_DecodeBoolean(data: *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn AMF_DecodeNumber(data: *const ::std::os::raw::c_char) -> f64;
    pub fn AMF_Encode(obj: *mut AMFObject,
                      pBuffer: *mut ::std::os::raw::c_char,
                      pBufEnd: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn AMF_EncodeEcmaArray(obj: *mut AMFObject,
                               pBuffer: *mut ::std::os::raw::c_char,
                               pBufEnd: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn AMF_EncodeArray(obj: *mut AMFObject,
                           pBuffer: *mut ::std::os::raw::c_char,
                           pBufEnd: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn AMF_Decode(obj: *mut AMFObject,
                      pBuffer: *const ::std::os::raw::c_char,
                      nSize: ::std::os::raw::c_int,
                      bDecodeName: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn AMF_DecodeArray(obj: *mut AMFObject,
                           pBuffer: *const ::std::os::raw::c_char,
                           nSize: ::std::os::raw::c_int,
                           nArrayLen: ::std::os::raw::c_int,
                           bDecodeName: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn AMF3_Decode(obj: *mut AMFObject,
                       pBuffer: *const ::std::os::raw::c_char,
                       nSize: ::std::os::raw::c_int,
                       bDecodeName: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn AMF_Dump(obj: *mut AMFObject);
    pub fn AMF_Reset(obj: *mut AMFObject);
    pub fn AMF_AddProp(obj: *mut AMFObject, prop: *const AMFObjectProperty);
    pub fn AMF_CountProp(obj: *mut AMFObject) -> ::std::os::raw::c_int;
    pub fn AMF_GetProp(obj: *mut AMFObject, name: *const AVal,
                       nIndex: ::std::os::raw::c_int)
     -> *mut AMFObjectProperty;
    pub fn AMFProp_GetType(prop: *mut AMFObjectProperty) -> AMFDataType;
    pub fn AMFProp_SetNumber(prop: *mut AMFObjectProperty, dval: f64);
    pub fn AMFProp_SetBoolean(prop: *mut AMFObjectProperty,
                              bflag: ::std::os::raw::c_int);
    pub fn AMFProp_SetString(prop: *mut AMFObjectProperty, str: *mut AVal);
    pub fn AMFProp_SetObject(prop: *mut AMFObjectProperty,
                             obj: *mut AMFObject);
    pub fn AMFProp_GetName(prop: *mut AMFObjectProperty, name: *mut AVal);
    pub fn AMFProp_SetName(prop: *mut AMFObjectProperty, name: *mut AVal);
    pub fn AMFProp_GetNumber(prop: *mut AMFObjectProperty) -> f64;
    pub fn AMFProp_GetBoolean(prop: *mut AMFObjectProperty)
     -> ::std::os::raw::c_int;
    pub fn AMFProp_GetString(prop: *mut AMFObjectProperty, str: *mut AVal);
    pub fn AMFProp_GetObject(prop: *mut AMFObjectProperty,
                             obj: *mut AMFObject);
    pub fn AMFProp_IsValid(prop: *mut AMFObjectProperty)
     -> ::std::os::raw::c_int;
    pub fn AMFProp_Encode(prop: *mut AMFObjectProperty,
                          pBuffer: *mut ::std::os::raw::c_char,
                          pBufEnd: *mut ::std::os::raw::c_char)
     -> *mut ::std::os::raw::c_char;
    pub fn AMF3Prop_Decode(prop: *mut AMFObjectProperty,
                           pBuffer: *const ::std::os::raw::c_char,
                           nSize: ::std::os::raw::c_int,
                           bDecodeName: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn AMFProp_Decode(prop: *mut AMFObjectProperty,
                          pBuffer: *const ::std::os::raw::c_char,
                          nSize: ::std::os::raw::c_int,
                          bDecodeName: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn AMFProp_Dump(prop: *mut AMFObjectProperty);
    pub fn AMFProp_Reset(prop: *mut AMFObjectProperty);
    pub fn AMF3CD_AddProp(cd: *mut AMF3ClassDef, prop: *mut AVal);
    pub fn AMF3CD_GetProp(cd: *mut AMF3ClassDef, idx: ::std::os::raw::c_int)
     -> *mut AVal;
}
